### PR TITLE
Show notification after failing login

### LINKED ISSUE #157: Add error message on login
On the login page the error message is missing, when username - password are not correct.

### PR DESCRIPTION
**Pull request by KordonDev**
closes #157

### CODE REVIEW

File: frontend/src/components/Login.vue [hunk 1]
```diff
@@ -47,11 +47,17 @@ export default class Login extends Vue {
   username = "";
   password = "";
   loggedIn = false;
+  loading = false;
 
   loginHandler() {
+    this.loading = true;
     login(this.username, this.password)
       .then(() => (this.loggedIn = true))
```
Comment (crymis) [inline frontend/src/components/Login.vue:55]:
```suggestion
      .then(() => {
        this.loading= false;
        this.loggedIn = true;
      })
```

File: frontend/src/components/Login.vue [hunk 2]
```diff
@@ -47,11 +47,17 @@ export default class Login extends Vue {
...
-      .then(() => this.$router.push("/"));
+      .then(() => this.$router.push("/"))
+      .catch(() => {
+        this.loading = false;
+        this.$toast.error("Login nicht erfolgreich. Benutzername oder Passwort falsch.")
```
Comment (crymis) [inline frontend/src/components/Login.vue:59]:
```suggestion
        this.$toast.error("Der Login war nicht erfolgreich. Benutzername oder Passwort falsch.")
```
